/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package de.huk.autoservice.demo.app

import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.web.servlet.MockMvc
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get
import org.springframework.test.web.servlet.result.MockMvcResultMatchers.status

@SpringBootTest
@AutoConfigureMockMvc
class AutoserviceControllerTest {

    @Autowired
    lateinit var mockMvc : MockMvc

    @Test
    fun `test index which should return http ok`() {
        mockMvc.perform(get("/")).andExpect(status().isOk)
    }
}
